import React from 'react';
import { useMonitoring } from '../monitoring/MonitoringProvider';

const DebugView: React.FC = () => {
  const { state, logError, clearErrors } = useMonitoring();

  const handleGenerateTestError = () => {
    logError({
      type: 'test',
      message: 'This is a test error generated by the debug view',
    });
  };

  const handleClearErrors = () => {
    clearErrors();
  };

  const handleResetStats = () => {
    // Implementation of handleResetStats function
  };

  return (
    <div className="debug-view">
      <div className="bg-[#ffffff] rounded-lg shadow p-6 mb-6">
        <h3 className="text-lg font-semibold mb-4">Debug Actions</h3>
        <div className="flex space-x-4">
          <button
            onClick={handleGenerateTestError}
            className="px-4 py-2 bg-yellow-500 text-white rounded hover:bg-yellow-600"
          >
            Generate Test Error
          </button>
          <button
            onClick={handleClearErrors}
            className="px-4 py-2 bg-[#eab308] text-[#ffffff] rounded hover:bg-[#ca8a04]"
          >
            Clear Errors
          </button>
          <button
            onClick={handleResetStats}
            className="px-4 py-2 bg-[#ef4444] text-[#ffffff] rounded hover:bg-[#dc2626]"
          >
            Reset Stats
          </button>
        </div>
      </div>

      <div className="bg-[#ffffff] rounded-lg shadow p-6">
        <h3 className="text-lg font-semibold mb-4">Error Log ({state.errors.length})</h3>
        {state.errors.length === 0 ? (
          <p className="text-gray-500">No errors recorded.</p>
        ) : (
          <div className="space-y-4">
            {state.errors.map((error, index) => (
              <div key={index} className="border-l-4 border-red-500 pl-4 py-2">
                <div className="flex justify-between">
                  <span className="font-medium">{error.type}</span>
                  <span className="text-sm text-gray-500">
                    {error.timestamp.toLocaleTimeString()}
                  </span>
                </div>
                <p className="text-gray-700">{error.message}</p>
                {error.agentId && (
                  <p className="text-sm text-gray-500">
                    Agent: {error.agentId}
                  </p>
                )}
                {error.taskId && (
                  <p className="text-sm text-gray-500">
                    Task: {error.taskId}
                  </p>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default DebugView; 